name: Pipeline CI/CD

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Executar testes unitários
        run: mvn test
      - name: Salvar relatórios de teste
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: target/surefire-reports

  build:
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Empacotar projeto
        run: mvn package
      - name: Salvar pacote JAR
        uses: actions/upload-artifact@v4
        with:
          name: pacote-jar
          path: target/*.jar

  notify:
    needs: [test, build]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificação por e-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Pipeline Executado com Status: ${{ needs.test.result == 'success' && needs.build.result == 'success' && 'Sucesso' || 'Falha' }}"
          body: |
            O pipeline no repositório ${{ github.repository }} foi concluído.
            Status dos Testes: ${{ needs.test.result }}
            Status do Build: ${{ needs.build.result }}
            Veja os detalhes da execução aqui: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: GitHub Actions Notifier <${{ secrets.MAIL_USERNAME }}>