name: Pipeline CI/CD

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Executar testes unitários
        run: mvn test
      - name: Salvar relatórios de teste
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: target/surefire-reports

  build:
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Empacotar projeto
        run: mvn package
      - name: Salvar pacote JAR
        uses: actions/upload-artifact@v4
        with:
          name: pacote-jar
          path: target/*.jar